/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.interfaz;
import basedatos.CRUD;
import basedatos.SQL;
import java.awt.event.KeyEvent;
import java.util.List;
import stock.Departamento;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stock.Proveedor;
/**
 *
 * @author fuent
 */
public class ProveedorDIALOG extends javax.swing.JDialog {

    List<Departamento> departamentos;
    //Proveedor proveedor;
    CRUD crud;
    private int idSeleccionado;
    Proveedor proveedor = new Proveedor();
    
    
    
    
    public ProveedorDIALOG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.crud = new CRUD();
        this.cargarDepartamentos();
        this.mostrarProveedor();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        boxDepartamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProveedor = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(727, 451));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre del proveedor:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Departamento:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 87, -1, -1));

        boxDepartamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxDepartamentoKeyPressed(evt);
            }
        });
        jPanel2.add(boxDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 84, 122, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Teléfono:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 87, -1, -1));

        btnInsertar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnInsertar.setText("Ingresar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 390, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 84, 122, -1));

        TablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProveedor);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 151, 634, 172));

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
this.crud = new CRUD();

        String nombre_proveedor = this.txtNombre.getText();
        String telefono =this.txtTelefono.getText();
        int indice = this.boxDepartamento.getSelectedIndex();
        int idDep = this.departamentos.get(indice).getId_departamento();


            proveedor.setTelefono(telefono);
            proveedor.setNombre_proveedor(nombre_proveedor);
            proveedor.setId_departamento(idDep);
            //Guardar en la base de datos

           boolean resultado = this.crud.insertar(SQL.insertProveedor(proveedor));
            if(resultado){
                JOptionPane.showMessageDialog(null,"Insertado correcatamente");
                this.mostrarProveedor();
            }else{
                JOptionPane.showMessageDialog(null,"No insertado");
            }  
            
            
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void TablaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProveedorMouseClicked
        
        
        this.btnActualizar.setEnabled(true);
        this.btnEliminar.setEnabled(true);

        
        int fila = this.TablaProveedor.getSelectedRow();

        this.idSeleccionado = Integer.parseInt(this.TablaProveedor.getValueAt(fila, 0).toString());

        System.out.println(this.idSeleccionado);

        try {
            ResultSet resultado = this.crud.seleccionar(SQL.selectProveedor(this.idSeleccionado));

            if (resultado.next()) {

                //this.txtNombre.setText(resultado.getNString());
                //this.boxDepartamento.addItem(resultado.getString(4));
                btnInsertar.setEnabled(false);

            }

        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }

        try {
            ResultSet resultado = this.crud.seleccionar(SQL.selectProveedor(this.idSeleccionado));

            if (resultado.next()) {

                
                this.txtNombre.setText(resultado.getString(2));
                this.txtTelefono.setText(resultado.getString(3));
                
                int id = resultado.getInt(4);
                for (int i=0; 1<this.departamentos.size(); i++){
                    
                    if(this.departamentos.get(i).getId_departamento()==id){
                    this.boxDepartamento.setSelectedItem(this.departamentos.get(i).getNombre());
                    break; 
                    }
                    
                }//cierre for

            }

        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_TablaProveedorMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        this.proveedor = new Proveedor();
        
        this.proveedor.setNombre_proveedor(txtNombre.getText());
        this.proveedor.setTelefono(txtTelefono.getText());
        
        int indice = this.boxDepartamento.getSelectedIndex();
        int idDep = this.departamentos.get(indice).getId_departamento();
        this.proveedor.setId_departamento(idDep);
        
        boolean result = this.crud.eliminarInsertar(SQL.actualizarProveedor(proveedor, this.idSeleccionado));
        if (result) {
            JOptionPane.showMessageDialog(null, "Actualizado correctamente");
            this.mostrarProveedor();
            
        } else {
            JOptionPane.showMessageDialog(null, "No actualizo");
        } 
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void boxDepartamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxDepartamentoKeyPressed
      if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_boxDepartamentoKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
       if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtTelefono.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
       if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            btnInsertar.requestFocus();
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       this.btnEliminar.setEnabled(false);
        this.btnActualizar.setEnabled(false);
        this.btnInsertar.setEnabled(true);

        this.txtNombre.setText("");
        this.txtTelefono.setText("");
        
        this.mostrarProveedor();
         boxDepartamento.setSelectedIndex(-1);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        boolean resultado = this.crud.eliminarInsertar(SQL.eliminarProveedor(this.idSeleccionado));

        if (resultado) {
            JOptionPane.showMessageDialog(null, "Eliminado correctamente");
            this.mostrarProveedor();
        } else {
            JOptionPane.showMessageDialog(null, "No eliminado correctamente");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
       //Limitamos el numero de caracteres
        if(txtTelefono.getText().length() == 10)
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedorDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedorDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedorDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedorDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProveedorDIALOG dialog = new ProveedorDIALOG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProveedor;
    private javax.swing.JComboBox<String> boxDepartamento;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

 private void cargarDepartamentos() {
        this.boxDepartamento.removeAllItems();
        
        try {
            ResultSet rst = this.crud.seleccionar(SQL.seletTodosDepartamento());
            
            Departamento dep;
            
            this.departamentos = new ArrayList();
            
            while (rst.next()) {                
                this.boxDepartamento.addItem(rst.getString(2));
                
               dep = new Departamento();
               
               dep.setId_departamento(rst.getInt(1));
               dep.setNombre(rst.getNString(2));
               
               this.departamentos.add(dep);
                
            }//cierra while
            
        } catch (SQLException e) {
            System.err.println("Error al cargar el departamento" + e.getMessage());
        }
        
    }//Cierro el motodo cargarDepartamentos
    
   
    private void mostrarProveedor() {
        this.limpiarTabla();
        DefaultTableModel modelo = (DefaultTableModel) TablaProveedor.getModel();
        modelo.addColumn("Id Proveedor");
        modelo.addColumn("Nombre");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Departamento");


        try {
            ResultSet resultado = this.crud.seleccionar(SQL.seletTodosProveedores());

            while (resultado.next()) {

                Object[] depAux = {resultado.getInt(1), resultado.getString(2), resultado.getString(3), resultado.getString(4)};//Obtenemos el id y el nombre  
                modelo.addRow(depAux);
            }//cierre de while

            this.TablaProveedor.setModel(modelo);

        } catch (SQLException e) {
            System.out.println("Error:" + e.getMessage());
    
        }
    }

    private void limpiarTabla() {
        TablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{}
        ));
    }
    

}
