/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.interfaz;

import basedatos.CRUD;
import basedatos.SQL;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stock.Departamento;
import stock.Proveedor;
import stock.Producto;

public class RegistroDIALOG extends javax.swing.JDialog {

    List<Departamento> departamentos;
    List<Proveedor> proveedor;
    CRUD crud;
    private int idSeleccionado;
    Producto producto;

    public RegistroDIALOG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.crud = new CRUD();
        this.cargarDepartamentos();

        this.mostrarProductos();
        this.setLocationRelativeTo(null);

        txtPrecioVenta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        boxDepartamento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        porcentaje = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtPrecioCosto = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(727, 451));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre producto:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 68, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Fecha de registro:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 235, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Cantidad:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 101, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Folio factura:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 268, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Departamento:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 301, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 390, 499, 10));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 65, 110, -1));

        txtFolio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFolioActionPerformed(evt);
            }
        });
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFolioKeyPressed(evt);
            }
        });
        jPanel2.add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 265, 110, -1));

        boxDepartamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDepartamentoActionPerformed(evt);
            }
        });
        boxDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxDepartamentoKeyPressed(evt);
            }
        });
        jPanel2.add(boxDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 298, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 32, 433, 318));

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        jLabel8.setText("Precio costo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 133, -1, -1));

        jLabel9.setText("Precio venta:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 195, -1, -1));

        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
        });
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 232, 110, -1));

        porcentaje.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                porcentajeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        porcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                porcentajeKeyPressed(evt);
            }
        });
        jPanel2.add(porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 159, 77, -1));

        jLabel10.setText("$");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 196, 20, 20));

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 98, 110, -1));

        txtPrecioCosto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrecioCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioCostoActionPerformed(evt);
            }
        });
        txtPrecioCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioCostoKeyPressed(evt);
            }
        });
        jPanel2.add(txtPrecioCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 131, 77, -1));

        txtPrecioVenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentaActionPerformed(evt);
            }
        });
        txtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyPressed(evt);
            }
        });
        jPanel2.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 193, 76, -1));

        jLabel12.setText("Ganacia:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 162, 76, -1));

        jLabel13.setText("%");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 162, -1, -1));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 412, 70, 20));

        jLabel14.setText("$");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 130, 10, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, 439, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void txtPrecioCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioCostoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void porcentajeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_porcentajeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentajeAncestorAdded

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void boxDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDepartamentoActionPerformed

    private void txtFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFolioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Producto producto = new Producto();

        String nombre = this.txtNombre.getText();
        int cantidad = Integer.parseInt(this.txtCantidad.getText());
        float pc = Float.parseFloat(this.txtPrecioCosto.getText()); //SQUI SE ENCUENTRA EL ERROR
        System.out.println(pc);
        float ganancias = ((Integer) this.porcentaje.getValue());
        float pv = pc + (pc * ganancias / 100);
        System.out.println(pv);
        String fecha = this.txtFecha.getText();
        String factura = this.txtFolio.getText();

        int indice = this.boxDepartamento.getSelectedIndex();

        int idDep = this.departamentos.get(indice).getId_departamento();

        producto.setNombre(nombre);
        producto.setCantidad(cantidad);
        producto.setPrecioCosto(pc);
        producto.setPrecioVenta(pv);
        producto.setFecha(fecha);
        producto.setFolio_factura(factura);
        producto.setId_departamento(idDep);

        boolean resultado = this.crud.insertProducto(producto);

        this.txtNombre.setText("");
        this.txtCantidad.setText("");
        this.txtPrecioCosto.setText("");
        this.txtPrecioVenta.setText("");
        this.txtFecha.setText("");
        this.txtFolio.setText("");
        boxDepartamento.setSelectedIndex(-1);

        if (resultado) {
            JOptionPane.showMessageDialog(null, "Producto insertado correctamente.");
            this.mostrarProductos();
        } else {
            JOptionPane.showMessageDialog(null, "Producto no insertado correctamente.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        boolean resultado = this.crud.eliminarInsertar(SQL.eliminarProducto(this.idSeleccionado));

        if (resultado) {
            JOptionPane.showMessageDialog(null, "Eliminado correctamente");
            this.mostrarProductos();
        } else {
            JOptionPane.showMessageDialog(null, "No eliminado correctamente");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        this.btnGuardar.setEnabled(false);
        this.btnActualizar.setEnabled(true);
        this.btnEliminar.setEnabled(true);

        int fila = this.jTable1.getSelectedRow();

        this.idSeleccionado = Integer.parseInt(this.jTable1.getValueAt(fila, 0).toString());

        System.out.println(this.idSeleccionado);

        try {
            ResultSet resultado = this.crud.seleccionar(SQL.selectProductosId(this.idSeleccionado));

            if (resultado.next()) {

                this.txtNombre.setText(resultado.getString(2));
                this.txtCantidad.setText(resultado.getString(3));
                this.txtPrecioCosto.setText(resultado.getString(4));
                this.txtPrecioVenta.setText(resultado.getString(5));
                this.txtFecha.setText(resultado.getString(6));
                this.txtFolio.setText(resultado.getString(7));

                //departamento 
                int id = resultado.getInt(8);
                for (int i = 0; 1 < this.departamentos.size(); i++) {

                    if (this.departamentos.get(i).getId_departamento() == id) {
                        this.boxDepartamento.setSelectedItem(this.departamentos.get(i).getNombre());
                        break;
                    }

                }//cierre for

            }

        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        this.producto = new Producto();

        this.producto.setNombre(this.txtNombre.getText());
        this.producto.setCantidad(Integer.parseInt(this.txtCantidad.getText()));

        float pc = Float.parseFloat(this.txtPrecioCosto.getText());
        this.producto.setPrecioCosto(pc);

        float ganancias = ((Integer) this.porcentaje.getValue());
        float pv = pc + (pc * ganancias / 100);
        this.producto.setPrecioVenta(pv);
        this.producto.setFecha(this.txtFecha.getText());
        this.producto.setFolio_factura(this.txtFolio.getText());

        int indice = this.boxDepartamento.getSelectedIndex();
        int idDep = this.departamentos.get(indice).getId_departamento();
        this.producto.setId_departamento(idDep);
        System.out.println("idDep = " + idDep);

        boolean result = this.crud.eliminarInsertar(SQL.actualizarProductos(producto, this.idSeleccionado));

        if (result) {
            JOptionPane.showMessageDialog(null, "Actualizado correctamente");
            this.mostrarProductos();

        } else {
            JOptionPane.showMessageDialog(null, "No actualizo");
        }


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPrecioCosto.requestFocus();
        }
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCantidad.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void porcentajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_porcentajeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtFecha.requestFocus();

            float pc = Float.parseFloat(this.txtPrecioCosto.getText()); //SQUI SE ENCUENTRA EL ERROR
            System.out.println(pc);
            float ganancias = ((Integer) this.porcentaje.getValue());
            float pv = pc + (pc * ganancias / 100);
            this.txtPrecioVenta.setText(String.valueOf(pv));
        }
    }//GEN-LAST:event_porcentajeKeyPressed

    private void txtPrecioVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtFecha.requestFocus();
        }
    }//GEN-LAST:event_txtPrecioVentaKeyPressed

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtFolio.requestFocus();
        }
    }//GEN-LAST:event_txtFechaKeyPressed

    private void txtFolioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boxDepartamento.requestFocus();
        }
    }//GEN-LAST:event_txtFolioKeyPressed

    private void txtPrecioCostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCostoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            porcentaje.requestFocus();
        }
    }//GEN-LAST:event_txtPrecioCostoKeyPressed

    private void boxDepartamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxDepartamentoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnGuardar.requestFocus();
        }
    }//GEN-LAST:event_boxDepartamentoKeyPressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.btnEliminar.setEnabled(false);
        this.btnActualizar.setEnabled(false);
        this.btnGuardar.setEnabled(true);

        this.txtNombre.setText("");
        this.txtCantidad.setText("");
        this.txtPrecioCosto.setText("");
        this.txtPrecioVenta.setText("");
        this.txtFecha.setText("");
        this.txtFolio.setText("");
        boxDepartamento.setSelectedIndex(-1);
        this.mostrarProductos();

    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroDIALOG dialog = new RegistroDIALOG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDepartamento;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner porcentaje;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioCosto;
    private javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables

    private void cargarDepartamentos() {
        this.boxDepartamento.removeAllItems();

        try {
            ResultSet rst = this.crud.seleccionar(SQL.seletTodosDepartamento());

            Departamento dep;

            this.departamentos = new ArrayList();

            while (rst.next()) {
                this.boxDepartamento.addItem(rst.getString(2));

                dep = new Departamento();

                dep.setId_departamento(rst.getInt(1));
                dep.setNombre(rst.getNString(2));

                this.departamentos.add(dep);

            }//cierra while

        } catch (SQLException e) {
            System.err.println("Error al cargar el departamento" + e.getMessage());
        }

    }//Cierro el motodo cargarDepartamentos

    private void mostrarProductos() {
        this.limpiarTabla();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.addColumn("Código de barra");
        modelo.addColumn("Nombre");

        try {
            ResultSet resultado = this.crud.seleccionar(SQL.selectProductos());

            while (resultado.next()) {

                Object[] depAux = {resultado.getString(1), resultado.getString(2)};//Obtenemos el id y el nombre  
                modelo.addRow(depAux);
            }//cierre de while

            this.jTable1.setModel(modelo);

        } catch (SQLException e) {
            System.out.println("Error:" + e.getMessage());

        }
    }//Cierre mostrar productos    

    private void limpiarTabla() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{}
        ));
    }

}//Cierre todo
